export default function getWeatherIconName ({ name, isDay }) {
    // icons https://bas.dev/work/meteocons
    const weatherIconNames = {
        'Sunny': 'clear-day',
        'Clear': 'clear-night',
        'Partly cloudy': `partly-cloudy-${isDay ? 'day' : 'night'}`,
        'Cloudy': 'cloudy',
        'Overcast': `overcast-${isDay ? 'day' : 'night'}`,
        'Mist': 'mist',
        'Patchy rain possible': `drizzle`,
        'Patchy snow possible': `partly-cloudy-${isDay ? 'day': 'night'}-snow`,
        'Patchy sleet possible': `sleet`,
        'Patchy freezing drizzle possible': `partly-cloudy-${isDay ? 'day': 'night'}-hail`,
        'Thundery outbreaks possible': 'rain',
        'Blowing snow': 'wind-snow',
        'Blizzard': `thunderstorms-${isDay ? 'day': 'night'}-snow`,
        'Fog': 'fog',
        'Freezing fog': 'haze',
        'Patchy light drizzle': `partly-cloudy-${isDay ? 'day' : 'night'}-drizzle`,
        'Light drizzle': 'drizzle',
        'Freezing drizzle': `partly-cloudy-${isDay ? 'day': 'night'}-sleet`,
        'Heavy freezing drizzle': `extreme-${isDay ? 'day': 'night'}-sleet`,
        'Patchy light rain': 'rain',
        'Light rain': 'rain',
        'Moderate rain at times': 'rain',
        'Moderate rain': 'rain',
        'Heavy rain at times': 'extreme-rain',
        'Heavy rain': 'extreme-rain',
        'Light freezing rain': 'sleet',
        'Moderate or heavy freezing rain': 'extreme-sleet',
        'Light sleet': 'sleet',
        'Moderate or heavy sleet': 'extreme-sleet',
        'Patchy light snow': `partly-cloudy-day-snow`,
        'Light snow': 'snow',
        'Patchy moderate snow': `overcast-${isDay ? 'day' : 'night'}-snow`,
        'Moderate snow': `extreme-${isDay ? 'day' : 'night'}-snow`,
        'Patchy heavy snow': 'extreme-snow',
        'Heavy snow': 'extreme-snow',
        'Ice pellets': 'hail',
        'Light rain shower': 'rain',
        'Moderate or heavy rain shower': 'extreme-rain',
        'Torrential rain shower': `thunderstorms-${isDay ? 'day' : 'night'}-rain`,
        'Light sleet showers': 'sleet',
        'Moderate or heavy sleet showers': 'extreme-sleet',
        'Light snow showers': `partly-cloudy-${isDay ? 'day': 'night'}-snow`,
        'Moderate or heavy snow showers': `extreme-${isDay ? 'day' : 'night'}-snow`,
        'Light showers of ice pellets': `partly-cloudy-${isDay ? 'day' : 'night'}-hail`,
        'Moderate or heavy showers of ice pellets': `extreme-${isDay ? 'day' : 'night'}-hail`,
        'Patchy light rain with thunder': `thunderstorms-${isDay ? 'day' : 'night'}-rain`,
        'Moderate or heavy rain with thunder': `thunderstorms-${isDay ? 'day' : 'night'}-extreme-rain`,
        'Patchy light snow with thunder': `thunderstorms-${isDay ? 'day' : 'night'}-snow`,
        'Moderate or heavy snow with thunder': `thunderstorms-${isDay ? 'day' : 'night'}-extreme-snow`,
    }

    return weatherIconNames[name]
}